// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using StoreAssistantPro.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace StoreAssistantPro.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AppConfigEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "StoreAssistantPro.Models.AppConfig",
                typeof(AppConfig),
                baseEntityType,
                propertyCount: 57,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var address = runtimeEntityType.AddProperty(
                "Address",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("Address", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<Address>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            address.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var backupEncryptionEnabled = runtimeEntityType.AddProperty(
                "BackupEncryptionEnabled",
                typeof(bool),
                propertyInfo: typeof(AppConfig).GetProperty("BackupEncryptionEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BackupEncryptionEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            backupEncryptionEnabled.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var backupIntervalHours = runtimeEntityType.AddProperty(
                "BackupIntervalHours",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("BackupIntervalHours", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BackupIntervalHours>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            backupIntervalHours.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var backupRetentionDays = runtimeEntityType.AddProperty(
                "BackupRetentionDays",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("BackupRetentionDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BackupRetentionDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            backupRetentionDays.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bankAccountNumber = runtimeEntityType.AddProperty(
                "BankAccountNumber",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("BankAccountNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BankAccountNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 30);
            bankAccountNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bankIFSC = runtimeEntityType.AddProperty(
                "BankIFSC",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("BankIFSC", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BankIFSC>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 11);
            bankIFSC.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var bankName = runtimeEntityType.AddProperty(
                "BankName",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("BankName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BankName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            bankName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var barcodeFormat = runtimeEntityType.AddProperty(
                "BarcodeFormat",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("BarcodeFormat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<BarcodeFormat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            barcodeFormat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var closingTime = runtimeEntityType.AddProperty(
                "ClosingTime",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("ClosingTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<ClosingTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 5);
            closingTime.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var compositionSchemeRate = runtimeEntityType.AddProperty(
                "CompositionSchemeRate",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("CompositionSchemeRate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<CompositionSchemeRate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            compositionSchemeRate.AddAnnotation("Relational:ColumnType", "decimal(5,2)");
            compositionSchemeRate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var currencyCode = runtimeEntityType.AddProperty(
                "CurrencyCode",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("CurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<CurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            currencyCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var currencySymbol = runtimeEntityType.AddProperty(
                "CurrencySymbol",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("CurrencySymbol", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<CurrencySymbol>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            currencySymbol.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dashboardWidgetLayout = runtimeEntityType.AddProperty(
                "DashboardWidgetLayout",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("DashboardWidgetLayout", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<DashboardWidgetLayout>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 4000);
            dashboardWidgetLayout.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dateFormat = runtimeEntityType.AddProperty(
                "DateFormat",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("DateFormat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<DateFormat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            dateFormat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var decimalPlaces = runtimeEntityType.AddProperty(
                "DecimalPlaces",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("DecimalPlaces", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<DecimalPlaces>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            decimalPlaces.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var email = runtimeEntityType.AddProperty(
                "Email",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("Email", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<Email>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            email.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var expenseApprovalThreshold = runtimeEntityType.AddProperty(
                "ExpenseApprovalThreshold",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("ExpenseApprovalThreshold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<ExpenseApprovalThreshold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            expenseApprovalThreshold.AddAnnotation("Relational:ColumnType", "decimal(18,2)");
            expenseApprovalThreshold.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var financialYearEndMonth = runtimeEntityType.AddProperty(
                "FinancialYearEndMonth",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("FinancialYearEndMonth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<FinancialYearEndMonth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            financialYearEndMonth.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var financialYearStartMonth = runtimeEntityType.AddProperty(
                "FinancialYearStartMonth",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("FinancialYearStartMonth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<FinancialYearStartMonth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            financialYearStartMonth.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var firmName = runtimeEntityType.AddProperty(
                "FirmName",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("FirmName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<FirmName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            firmName.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fontScalePercent = runtimeEntityType.AddProperty(
                "FontScalePercent",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("FontScalePercent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<FontScalePercent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            fontScalePercent.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var gSTNumber = runtimeEntityType.AddProperty(
                "GSTNumber",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("GSTNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<GSTNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 15);
            gSTNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var goldTierThreshold = runtimeEntityType.AddProperty(
                "GoldTierThreshold",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("GoldTierThreshold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<GoldTierThreshold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            goldTierThreshold.AddAnnotation("Relational:ColumnType", "decimal(18,2)");
            goldTierThreshold.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var gstRegistrationType = runtimeEntityType.AddProperty(
                "GstRegistrationType",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("GstRegistrationType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<GstRegistrationType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            gstRegistrationType.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var heldBillTimeoutMinutes = runtimeEntityType.AddProperty(
                "HeldBillTimeoutMinutes",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("HeldBillTimeoutMinutes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<HeldBillTimeoutMinutes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            heldBillTimeoutMinutes.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var invoicePrefix = runtimeEntityType.AddProperty(
                "InvoicePrefix",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("InvoicePrefix", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<InvoicePrefix>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            invoicePrefix.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var invoiceResetPeriod = runtimeEntityType.AddProperty(
                "InvoiceResetPeriod",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("InvoiceResetPeriod", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<InvoiceResetPeriod>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            invoiceResetPeriod.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var isDefaultAdminPin = runtimeEntityType.AddProperty(
                "IsDefaultAdminPin",
                typeof(bool),
                propertyInfo: typeof(AppConfig).GetProperty("IsDefaultAdminPin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<IsDefaultAdminPin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isDefaultAdminPin.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var isInitialized = runtimeEntityType.AddProperty(
                "IsInitialized",
                typeof(bool),
                propertyInfo: typeof(AppConfig).GetProperty("IsInitialized", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<IsInitialized>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isInitialized.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var isStockFrozen = runtimeEntityType.AddProperty(
                "IsStockFrozen",
                typeof(bool),
                propertyInfo: typeof(AppConfig).GetProperty("IsStockFrozen", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<IsStockFrozen>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isStockFrozen.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var labelPaperSize = runtimeEntityType.AddProperty(
                "LabelPaperSize",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("LabelPaperSize", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<LabelPaperSize>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            labelPaperSize.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var lastUpdateCheck = runtimeEntityType.AddProperty(
                "LastUpdateCheck",
                typeof(DateTime?),
                propertyInfo: typeof(AppConfig).GetProperty("LastUpdateCheck", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<LastUpdateCheck>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUpdateCheck.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var licenseKey = runtimeEntityType.AddProperty(
                "LicenseKey",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("LicenseKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<LicenseKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            licenseKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var logoPath = runtimeEntityType.AddProperty(
                "LogoPath",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("LogoPath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<LogoPath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);
            logoPath.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var loyaltyPointsRate = runtimeEntityType.AddProperty(
                "LoyaltyPointsRate",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("LoyaltyPointsRate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<LoyaltyPointsRate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            loyaltyPointsRate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var masterPinHash = runtimeEntityType.AddProperty(
                "MasterPinHash",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("MasterPinHash", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<MasterPinHash>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            masterPinHash.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var maxDiscountPercent = runtimeEntityType.AddProperty(
                "MaxDiscountPercent",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("MaxDiscountPercent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<MaxDiscountPercent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            maxDiscountPercent.AddAnnotation("Relational:ColumnType", "decimal(5,2)");
            maxDiscountPercent.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var maxHeldBillsPerUser = runtimeEntityType.AddProperty(
                "MaxHeldBillsPerUser",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("MaxHeldBillsPerUser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<MaxHeldBillsPerUser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            maxHeldBillsPerUser.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var monthlySalesTarget = runtimeEntityType.AddProperty(
                "MonthlySalesTarget",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("MonthlySalesTarget", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<MonthlySalesTarget>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            monthlySalesTarget.AddAnnotation("Relational:ColumnType", "decimal(18,2)");
            monthlySalesTarget.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var numberFormat = runtimeEntityType.AddProperty(
                "NumberFormat",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("NumberFormat", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<NumberFormat>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            numberFormat.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var openingTime = runtimeEntityType.AddProperty(
                "OpeningTime",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("OpeningTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<OpeningTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 5);
            openingTime.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pANNumber = runtimeEntityType.AddProperty(
                "PANNumber",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("PANNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<PANNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 10);
            pANNumber.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var phone = runtimeEntityType.AddProperty(
                "Phone",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("Phone", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<Phone>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 15);
            phone.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pincode = runtimeEntityType.AddProperty(
                "Pincode",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("Pincode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<Pincode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 6);
            pincode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var platinumTierThreshold = runtimeEntityType.AddProperty(
                "PlatinumTierThreshold",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("PlatinumTierThreshold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<PlatinumTierThreshold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            platinumTierThreshold.AddAnnotation("Relational:ColumnType", "decimal(18,2)");
            platinumTierThreshold.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var quotationTermsAndConditions = runtimeEntityType.AddProperty(
                "QuotationTermsAndConditions",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("QuotationTermsAndConditions", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<QuotationTermsAndConditions>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2000);
            quotationTermsAndConditions.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var receiptFooterText = runtimeEntityType.AddProperty(
                "ReceiptFooterText",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("ReceiptFooterText", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<ReceiptFooterText>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            receiptFooterText.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var receiptHeaderText = runtimeEntityType.AddProperty(
                "ReceiptHeaderText",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("ReceiptHeaderText", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<ReceiptHeaderText>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            receiptHeaderText.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var silverTierThreshold = runtimeEntityType.AddProperty(
                "SilverTierThreshold",
                typeof(decimal),
                propertyInfo: typeof(AppConfig).GetProperty("SilverTierThreshold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<SilverTierThreshold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            silverTierThreshold.AddAnnotation("Relational:ColumnType", "decimal(18,2)");
            silverTierThreshold.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var singletonKey = runtimeEntityType.AddProperty(
                "SingletonKey",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("SingletonKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<SingletonKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: 0);
            singletonKey.AddAnnotation("Relational:DefaultValue", 1);
            singletonKey.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var soundEffectsEnabled = runtimeEntityType.AddProperty(
                "SoundEffectsEnabled",
                typeof(bool),
                propertyInfo: typeof(AppConfig).GetProperty("SoundEffectsEnabled", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<SoundEffectsEnabled>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            soundEffectsEnabled.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var startupMode = runtimeEntityType.AddProperty(
                "StartupMode",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("StartupMode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<StartupMode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 20);
            startupMode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            state.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var stateCode = runtimeEntityType.AddProperty(
                "StateCode",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("StateCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<StateCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2);
            stateCode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var stockAdjustmentApprovalThreshold = runtimeEntityType.AddProperty(
                "StockAdjustmentApprovalThreshold",
                typeof(int),
                propertyInfo: typeof(AppConfig).GetProperty("StockAdjustmentApprovalThreshold", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<StockAdjustmentApprovalThreshold>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            stockAdjustmentApprovalThreshold.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var themeMode = runtimeEntityType.AddProperty(
                "ThemeMode",
                typeof(string),
                propertyInfo: typeof(AppConfig).GetProperty("ThemeMode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AppConfig).GetField("<ThemeMode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            themeMode.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { singletonKey },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AppConfigs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
