// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using StoreAssistantPro.Data;
using StoreAssistantPro.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
